// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OOP_final_project.Data;

#nullable disable

namespace OOP_final_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251213135157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OOP_final_project.GlobalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GlobalUsers");

                    b.HasDiscriminator().HasValue("GlobalUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OOP_final_project.Doctor", b =>
                {
                    b.HasBaseType("OOP_final_project.GlobalUser");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkRoom")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("OOP_final_project.Nurse", b =>
                {
                    b.HasBaseType("OOP_final_project.GlobalUser");

                    b.Property<string>("WorkArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Nurse");
                });

            modelBuilder.Entity("OOP_final_project.Patient", b =>
                {
                    b.HasBaseType("OOP_final_project.GlobalUser");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Illness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AssignedDoctorId");

                    b.HasDiscriminator().HasValue("Patient");
                });

            modelBuilder.Entity("OOP_final_project.Patient", b =>
                {
                    b.HasOne("OOP_final_project.Doctor", "AssignedDoctor")
                        .WithMany()
                        .HasForeignKey("AssignedDoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedDoctor");
                });
#pragma warning restore 612, 618
        }
    }
}
